### ISSUE TITLE
Erro ao rodar o projeto

### ISSUE THREAD

**Issue by ddvargas** [GMob-UFSM/ELC1001.Frontend#1]
Ao rodar os comandos `./gradlew clean && ./gradlew :app:bundleRelease` tudo funciona bem e termina sem erros. Porém ao voltar ao root do projeto e tentar rodar `react-native run-android` me dá o seguinte erro:

> react-native run-android

>error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a new location. Run CLI with --verbose flag for more 
details.
npm verb lifecycle Baloo@0.0.1android: unsafe-perm in lifecycle true
npm verb lifecycle Baloo@0.0.1android: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\varga\Documents\SistemasDeInformacao-OFF\ComputacaoMovelOFF\Tentativa2\ProjetoApp\ELC1001.Frontend\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\apache-maven-3.6.0\bin;C:\Program Files\PuTTY\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Users\varga\AppData\Local\Android\Sdk\platform-tools\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;"C:\Users\varga\AppData\Local\Android\Sdk\tools;C:\Users\varga\AppData\Local\Android\Sdk\platform-tools";C:\Program Files\Java\jdk1.8.0_251\bin;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Windows\System32\;C:\Program Files\nodejs\;C:\Users\varga\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5\bin;;C:\apache-maven-3.6.0\bin;C:\Users\varga\AppData\Local\Yarn\bin;C:\Users\varga\AppData\Roaming\npm
npm verb lifecycle Baloo@0.0.1android: CWD: C:\Users\varga\Documents\SistemasDeInformacao-OFF\ComputacaoMovelOFF\Tentativa2\ProjetoApp\ELC1001.Frontend
npm info lifecycle Baloo@0.0.1android: Failed to exec android script
npm verb stack Error: Baloo@0.0.1 android: `react-native run-android`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1051:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid Baloo@0.0.1
npm verb cwd C:\Users\varga\Documents\SistemasDeInformacao-OFF\ComputacaoMovelOFF\Tentativa2\ProjetoApp\ELC1001.Frontend\android
npm verb Windows_NT 10.0.18363
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "android" "--verbose"   
npm verb node v14.2.0
npm ERR! errno 1
npm ERR! Baloo@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Baloo@0.0.1 android script.
npm timing npm Completed in 63845ms
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\varga\AppData\Roaming\npm-cache\_logs\2020-05-07T23_50_31_966Z-debug.log

Estou usando:
   Windows 10 64bits,
   Visual Studio,
   npm 6.14.4, 
   node v14.2.0, 
   react-native-cli: 2.0.1
   react-native: 0.62.2

**Comment by victorCuri** [comment]
Fala Daniel! Tu saiu da pasta android? 

cd ..

**Comment by ddvargas** [comment]
sim, tinha certeza que estava fora da pasta android, mas desinstalei tudo e funcionou, depois.

**Comment by victorCuri** [comment]
Beleza! Esse erro normalmente também ocorre por incompatibilidade entre versões de pacotes. Qualquer coisa que precisar, é só chamar.
